- name: Add disk to Azure VM
  hosts: all
  tasks:
    - name: install python package
      pip:
        name: setuptools

    - name: Create managed disk
      azure_rm_manageddisk:
        name: harshalmanageddisk
        resource_group: HarshalRG
        disk_size_gb: 1

    - name: Mount the managed disk to VM
      azure_rm_manageddisk:
        name: harshalmanageddisk
        resource_group: HarshalRG
        disk_size_gb: 1
        managed_by: harshalVM
        attach_caching: read_only